### ISSUE TITLE
--print-colors error

### ISSUE THREAD

**Issue by Ansen-A** [jordimas/whisper-ctranslate2#1]
Hi，When I use --print-colors, an error message appears. What is the problem?

My input is as follows:
whisper-ctranslate2 .\test\main.wav --language zh --model large-v2 --device cuda --output_dir .\test\output-ctranslate_cuda_large_v2_float32 --print-colors
The error message is as follows:
error: argument --print-colors: expected one argument.

It runs normally without this option.

**Comment by jordimas** [comment]
Hello!

Two things to check:

- Make sure that you have version 0.0.9 (it's not supported in previous versions)
- You need to indicate ' --print-colors True'. It follows the same pattern that the original OpenAI client for new boolean options

Regards

Jordi,

**Comment by Ansen-A** [comment]
Hi Jordi
It can work now, thank you.

Ansen
