### ISSUE TITLE
Output file location

### ISSUE THREAD

**Issue by Zacharie-Jacob** [jordimas/whisper-ctranslate2#10]
The help specifies that the output files should be written to the directory I am running whisper-ctranslate2 from, but it does not appear to be writing anything out at all.  I am unsure whether it is writing any files at all, or if the paths are doing something really unconventional like the .dll problems that have been mentioned elsewhere.

I am using --task translate  and running this from a Windows cmd terminal.  The regular version of Whisper outputs all of the files to the directory, but this does not appear to produce anything.

It looks like this specifically applies to the Translate task.  Transcribe generates the expected outputs in the expected spot.

EDIT:  It looks like it depends on what model I am using?  Medium will complete on a larger file, when large-v1 and large-v2 finish the translation but do not produce any output files.    large-v1 will work on a smaller test file that I made, whereas large-v2 will not produce any output files I can see.

**Comment by jordimas** [comment]
Hello. I'm using Linux (not Windows, sorry) and --task translate and --task transcribe work well for me,  they produce the expected files.

Some comments:

1. Make sure that you have installed the latest version (version 0.14) of whisper-ctranslate2
2. The fact that transcribe or translate tasks work sometime for me discards any problem with CUDA drivers and similar

Different models have different memory requirements, large models need more memory than medium or small. It looks to me that you may not have enough memory.

Are you using GPU or CPU for inference? How much memory do you have?

**Comment by Zacharie-Jacob** [comment]
Looks like I was just wrong on what the distinction is.  It appears that I just can't get output for larger files (those over an hour, but I haven't done exact testing for what works and what doesn't.

Small files (several minute files used for testing) will produce output srt and vtt files, etc. for both Transcribe and Translate.  

Larger files will display the full transcription or translation to the cmd terminal display, but will not write any files at the end.

I guess the entire thread is fundamentally flawed after this additional testing.  There is a problem but it is not what I originally though.

**Comment by jordimas** [comment]
I'm going to close this. If you need further help please re-open this issue. Thanks

**Comment by Zacharie-Jacob** [comment]
Yeah, this is fine to close.  Maybe my problem will resolve itself once I have everything reinstalled properly. Something is wrong with something if all files display the translation to the terminal but only some write output files with no errors or warnings, but there is no reason to think it is an issue with whisper-ctranslate2 specifically.
