### ISSUE TITLE
Support additional params for `faster-whisper` VAD options

### ISSUE THREAD

**Issue by mayeaux** [jordimas/whisper-ctranslate2#13]
`faster-whisper` now supports passing additional parameters to the VAD:

https://github.com/guillaumekln/faster-whisper/blob/master/faster_whisper/vad.py#L15

I might take a crack at this but probably won't have a chance for a couple days

**Comment by jordimas** [comment]
Thanks. This has been implemented in whisper-ctranslate latest version.
