### ISSUE TITLE
Live Inference API

### ISSUE THREAD

**Issue by aqibsaeed** [jordimas/whisper-ctranslate2#18]
Hi Jordi, 

Thanks for open sourcing it! Could you please provide an example of running live inference programmatically instead of via CLI?  Thanks.

**Comment by jordimas** [comment]
Sure

_whisper-ctranslate2 --live_transcribe True_ 

You can also all available parameters, for example:

_whisper-ctranslate2 --live_transcribe True  --model large-v2 --language en_

I will do improve the documentation.
