### ISSUE TITLE
Enable GPU

### ISSUE THREAD

**Issue by fleeasura123** [jordimas/whisper-ctranslate2#19]
Hi sir, How to enable GPU mode. I managed to run it but it uses my CPU and not using my GPU. Thank you!

**Comment by jordimas** [comment]
Hello

I added in the [readme](https://github.com/jordimas/whisper-ctranslate2/blob/main/README.md) a section called **CPU and GPU support** which hopefully clarify this.

**Comment by fleeasura123** [comment]
Thank you!
