### ISSUE TITLE
No file output if output folder/type not selected

### ISSUE THREAD

**Issue by rsmith02ct** [jordimas/whisper-ctranslate2#20]
Using whisper-ctranslate2 0.1.8 (Windows 11 Pro  64 bit build 22621)  I am not getting any transcription output if I don't select a type/location for it.
![image](https://user-images.githubusercontent.com/122251109/232277518-79734c26-ec62-47e6-8a51-22b5447babe0.png)

Text is generated but nothing is output at C:\Users\rsmit\Dropbox\Videos

Using this command line: whisper-ctranslate2.exe --language en --model "base" --device CPU --output_dir "C:\Users\rsmit\Dropbox\Videos" --output_format "srt" "C:\Users\rsmit\Dropbox\Videos\080109-002.wav"

I get a SRT file in that folder with the contents: 
1
00:00:00,000 --> 00:00:07,280
Hi, this is Roger Smith with the U.S. Base Conservation Group, my dearth.

**Comment by ZhengLiu97** [comment]
I used
```
whisper-ctranslate2.exe --language en --model "base" --device CPU --output_dir "D:\" --output_format "srt" ".\Day01.wav"
```
And I got nothing. The terminal warned me, but no error showed up!
![image](https://user-images.githubusercontent.com/65115609/232278826-e5b2deb1-0551-41ff-b647-be77403a16f1.png)

**Comment by Purfview** [comment]
Try `whisper-ctranslate2 0.1.9` from that post: https://github.com/jordimas/whisper-ctranslate2/issues/15#issuecomment-1510109193

**Comment by jordimas** [comment]
@ZhengLiu97 If you can please open a seperate issue specifying which operating system version, whisper-ctranslate2 version, etc.

**Comment by jordimas** [comment]
@rsmith02ct I cannot reproduce the problem. I spin off a Windows Box with the same versions and I just cannot reproduce.

If you can please run:
* whisper-ctranslate2.exe file.wav
* whisper-ctranslate2.exe file.wav --output_dir directory
* whisper-ctranslate2.exe file.wav --output_dir --output_format "srt" 

I'm trying to understand if what makes this work for you is a) specifying only  --output_dir,  b) specifying only --output_format or  c) specifying both --output_dir and --output_format

**Comment by rsmith02ct** [comment]
Sure, happy to report what's going on specifically. 

Here are three command lines. 

whisper-ctranslate2.exe file.wav "C:\Users\rsmit\Dropbox\Videos\080109-002.wav"

whisper-ctranslate2.exe "C:\Users\rsmit\Dropbox\Videos\080109-002.wav" --output_dir "C:\Users\rsmit\Dropbox\Videos"

whisper-ctranslate2.exe "C:\Users\rsmit\Dropbox\Videos\080109-002.wav" --output_dir "C:\Users\rsmit\Dropbox\Videos" --output_format "srt"

All three of them don't work.  No text appears in the command prompt window and no files are output:

   whisper-ctranslate2.exe "C:\Users\rsmit\Dropbox\Videos\080109-002.wav"

   whisper-ctranslate2.exe "C:\Users\rsmit\Dropbox\Videos\080109-002.wav" --output_dir "C:\Users\rsmit\Dropbox\Videos"

   whisper-ctranslate2.exe "C:\Users\rsmit\Dropbox\Videos\080109-002.wav" --output_dir "C:\Users\rsmit\Dropbox\Videos" --output_format "srt"

Second try 
whisper-ctranslate2.exe --device CPU "C:\Users\rsmit\Dropbox\Videos\080109-002.wav"

Shows text in the command line window but no files are output into the folder with the source video (I assume that's where it would go?)

whisper-ctranslate2.exe --device CPU "C:\Users\rsmit\Dropbox\Videos\080109-002.wav" --output_dir "C:\Users\rsmit\Dropbox\Videos"

Outputs a .json, srt, tsv, txt and vtt in C:\Users\rsmit\Dropbox\Videos

whisper-ctranslate2.exe --device CPU "C:\Users\rsmit\Dropbox\Videos\080109-002.wav" --output_dir "C:\Users\rsmit\Dropbox\Videos" --output_format "srt"

Outputs a srt in C:\Users\rsmit\Dropbox\Videos

**Comment by Purfview** [comment]
> whisper-ctranslate2.exe --device CPU "C:\Users\rsmit\Dropbox\Videos\080109-002.wav"
> 
> Shows text in the command line window but no files are output into the folder with the source video (I assume that's where it would go?)

You should look in a folder where is your executable located.

**Comment by rsmith02ct** [comment]
Really, it defaults there? I didn't have that folder open. 

Okay, so:

whisper-ctranslate2.exe --device CPU "C:\Users\rsmit\Dropbox\Videos\080109-002.wav"

Output json, srt, tsv, txt, vtt in C:\Users\rsmit\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts

So this issue's resolved, my remaining problem is just CUDA. Thank you.

**Comment by jordimas** [comment]
Thanks. This has been a good discussion. Now when in verbose mode the tool displays the output directory to make sure that everybody is clear were the files are:

https://github.com/jordimas/whisper-ctranslate2/commit/bcea4cda338cd79934e894a7afa3a99ed710ae10

**Comment by Purfview** [comment]
> Really, it defaults there?

Don't you remember? A ~month ago you asked me same thing about whisper-OpenAI. :)
