### ISSUE TITLE
Documentation for translation functionality?

### ISSUE THREAD

**Issue by rsmith02ct** [jordimas/whisper-ctranslate2#23]
Is it possible to use ctranslate to detect audio and then translate it into a target language from the command line prompt? I searched for documentation and while I see a translate flag and a language flag it's not clear to me if that's the source or target language.

For one English video I mistakenly flagged it as Japanese and ended up getting more or less a Japanese translation with timecode which shocked me. I wasn't able to replicate this on purpose with another file though where I actually wanted it to be translated (despite telling it translate and Japanese it just gave me an English transcription). 

It would be great if the help were a little more explicit about the options and how to set them.

**Comment by jordimas** [comment]
Whisper model provides translation from any of the supported languages to English and this is what's is officially supported by the model. I will improve the documentation to explain this.

I have experience also what you explain, but this is not supported by the Whisper model and does not work well.

**Comment by rsmith02ct** [comment]
Thanks, I appreciate documentation for how to use it the right way. It could be a great timesaver.

**Comment by jordimas** [comment]
Basically is that I added here:

https://github.com/jordimas/whisper-ctranslate2/commit/ac89ab4024eaf19a3dff4fdbf7c882530f1d3175

If you still have questions, please let me know.
