### ISSUE TITLE
Multi audio input support?

### ISSUE THREAD

**Issue by keimaruO** [jordimas/whisper-ctranslate2#8]
I’ve tried running whisper-ctranslate2 with multiple audio files using a command like `whisper-ctranslate2 1.opus 2.opus`, as shown in the official example, but it doesn’t seem to work. Is it possible to add support for processing multiple input files at once?

If there’s a way to do this, could you please advise?

**Comment by keimaruO** [comment]
I’ve resolved the issue. What I did was completely uninstall both the official Whisper and whisper-ctranslate2, then reinstall them to get the latest versions

With the official Whisper command, using `whisper 1.opus 2.opus` alone would automatically handle multiple audio files and generate subtitle files for them. However, with whisper-ctranslate2, this functionality is not included, so you need to add commands like `--output_dir "/output"` and `--output_format all`

**Comment by jordimas** [comment]
If do run **whisper-ctranslate2 1.opus 2.opus**  it creates the following files:

1.json
1.srt
1.tsv
1.txt
1.vtt
2.json
2.srt
2.tsv
2.txt
2.vtt

By default uses the "." directory and all formats. Can you confirm that this is not working for you? Thanks

**Comment by jordimas** [comment]
I'm going to close this issue. If you have any more concrete data, please re-open the issue. Thanks
