### ISSUE TITLE
.DLL's needed to run on Windows Anaconda command prompt

### ISSUE THREAD

**Issue by turnkit** [jordimas/whisper-ctranslate2#9]
Spent several hours trying to get this working under Anaconda under Windows (after failing to get it to work in Ubuntu WSL2) with the GPU.

What's needed are the cblasLt64_12.dll and the CUDNN... dll's -- and this is the tricky part -- also needed is zlibwapi.dll 

I put them all in the C:\Users\[username]\anaconda3\Lib\site-packages\ctranslate2 folder with the other dll's and it finally worked.

honestly have forgetting which downloads included the nvidia dll's but I think some where in the cuda_12.1.0_531.14_windows.exe which I opened with 7zip to extract.  Probably didn't install "correctly" but seems to be working okay now.

Thanks for all the work as the speed is great!

https://i.stack.imgur.com/PXtpG.png

**Comment by jordimas** [comment]
Thanks for sharing your experience

Instead of copying the files to the CTranslate2 folder, it should work if these files are in the paths included in the _LD_LIBRARY_PATH- environment variable. Can you check if this will work for you? Thanks

**Comment by CyberLykan** [comment]
Looks like the .dll's required are:
cublas64_11.dll
cublasLt64_11.dll
cudnn_cnn_infer64_8.dll
cudnn_ops_infer64_8.dll
cudnn64_8.dll
zlibwapi.dll

**Comment by Zacharie-Jacob** [comment]
Was this ever really resolved?    I do not understand why this or Ctranslate2 have troubles finding the cudnn files when regular Whisper does not.    There must be some actual cause here.
